config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"]}
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: 0..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    # find the restaurant that we want to add the review to
    @review = Review.new(review_params)
    # create new review using strong params
    @review.restaurant = @restaurant
    # link the review to a restaurant, connect the foreign keys
    if @review.save
      # if true (it passes validations) it will go to redirect
      redirect_to restaurant_path(@restaurant)
    else
      # if false (it does not pass validations)
      render :new
    end
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <!-- app/views/layouts/application.html.erb -->
<head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- [...] -->
</head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurant_path(restaurant.id) %>
    <%= restaurant.address %>
    <%= restaurant.phone_number %>
    <%= restaurant.category %>
  </li>
  <% end %>
</ul>
<%= link_to "Add new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category %>
<%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><strong>Address</strong>
  <%= @restaurant.address %></p>
<p><strong>Phone Number</strong>
  <%= @restaurant.phone_number %></p>
<p><strong>Category</strong>
  <%= @restaurant.category %></p>
<%= link_to "Back to restaurants", restaurants_path  %>
<%= link_to "Add a review", new_restaurant_review_path(@restaurant.id) %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>
<%= link_to  %>